version: '3.8'

networks:
  backend-network:
    driver: bridge

services:
  postgres:
    container_name: interact-postgres-db
    image: postgres:16
    restart: always
    ports:
      - "5432:${DB_PORT}"
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${DB_NAME}", "-U", "${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 3

volumes:
  postgres:
    name: postgres-db
    driver: local